FROM node:latest


# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json to the container
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application source code to the container
COPY . .

# Expose a port for the application to listen on (change as needed)
EXPOSE 8080

# Define the command to run your application
CMD ["npm","run","start"]
